declare module "*react-input-emoji"
declare module "*@tanstack/react-query-devtools"
declare module "*redux-persist"
declare module "*redux-persist/integration/react"
declare module "*redux-persist/lib/storage"
declare module "*react"